// Stable semantic IDs shared by ReRevved's public C ABIs.

#pragma once

#include <stdint.h>

typedef int32_t CivilizationId;
typedef int32_t UnitTypeId;
typedef int32_t UnitIdentityId;
typedef int32_t UnitDisplayForm;
typedef int32_t TerrainId;

enum
{
    TERRAIN_UNKNOWN  = -1,
    TERRAIN_SEA      = 0,
    TERRAIN_PLAINS   = 1,
    TERRAIN_FOREST   = 2,
    TERRAIN_HILL     = 3,
    TERRAIN_DESERT   = 4,
    TERRAIN_MOUNTAIN = 5,
    TERRAIN_COUNT    = 6,
};

enum
{
    CIVILIZATION_UNKNOWN   = -1,
    CIVILIZATION_ROMAN     = 0,
    CIVILIZATION_EGYPTIAN  = 1,
    CIVILIZATION_GREEK     = 2,
    CIVILIZATION_SPANISH   = 3,
    CIVILIZATION_GERMAN    = 4,
    CIVILIZATION_RUSSIAN   = 5,
    CIVILIZATION_CHINESE   = 6,
    CIVILIZATION_AMERICAN  = 7,
    CIVILIZATION_JAPANESE  = 8,
    CIVILIZATION_FRENCH    = 9,
    CIVILIZATION_INDIAN    = 10,
    CIVILIZATION_ARABIAN   = 11,
    CIVILIZATION_AZTEC     = 12,
    CIVILIZATION_ZULU      = 13,
    CIVILIZATION_MONGOLIAN = 14,
    CIVILIZATION_ENGLISH   = 15,
    CIVILIZATION_COUNT     = 16,
};

enum
{
    UNIT_TYPE_UNKNOWN             = -1,
    UNIT_TYPE_SETTLERS            = 0,
    UNIT_TYPE_FSETTLER            = 1,
    UNIT_TYPE_NAVAL_CREW          = 2,
    UNIT_TYPE_BARBARIAN_HOT       = 3,
    UNIT_TYPE_BARBARIAN_TEMPERATE = 4,
    UNIT_TYPE_BARBARIAN_COLD      = 5,
    UNIT_TYPE_WARRIOR             = 6,
    UNIT_TYPE_MILITIA             = 7,
    UNIT_TYPE_LEGION              = 8,
    UNIT_TYPE_ARCHER              = 9,
    UNIT_TYPE_RIFLEMEN            = 10,
    UNIT_TYPE_MODERN_INFANTRY     = 11,
    UNIT_TYPE_HORSEMEN            = 12,
    UNIT_TYPE_KNIGHTS             = 13,
    UNIT_TYPE_TANK                = 14,
    UNIT_TYPE_PHALANX             = 15,
    UNIT_TYPE_CATAPULT            = 16,
    UNIT_TYPE_CANNON              = 17,
    UNIT_TYPE_ARTILLERY           = 18,
    UNIT_TYPE_SUBMARINE           = 19,
    UNIT_TYPE_GALLEY              = 20,
    UNIT_TYPE_GALLEON             = 21,
    UNIT_TYPE_CRUISER             = 22,
    UNIT_TYPE_BATTLESHIP          = 23,
    UNIT_TYPE_SPACE_STATION       = 24,
    UNIT_TYPE_BOMBER              = 25,
    UNIT_TYPE_FIGHTER             = 26,
    UNIT_TYPE_ICBM                = 27,
    UNIT_TYPE_SPY                 = 28,
    UNIT_TYPE_COUNT               = 29,
};

enum
{
    UNIT_IDENTITY_BASE             = 0,
    UNIT_IDENTITY_JAGUAR_WARRIOR   = 1,
    UNIT_IDENTITY_IMPI_WARRIOR     = 2,
    UNIT_IDENTITY_ASHIGARU_PIKEMEN = 3,
    UNIT_IDENTITY_HOPLITE          = 4,
    UNIT_IDENTITY_LONGBOW_ARCHER   = 5,
    UNIT_IDENTITY_CROSSBOW_ARCHER  = 6,
    UNIT_IDENTITY_TREBUCHET        = 7,
    UNIT_IDENTITY_COSSACK_HORSEMAN = 8,
    UNIT_IDENTITY_SAMURAI_KNIGHT   = 9,
    UNIT_IDENTITY_CONQUISTADOR     = 10,
    UNIT_IDENTITY_PANZER_TANK      = 11,
    UNIT_IDENTITY_T34_TANK         = 12,
    UNIT_IDENTITY_SHERMAN_TANK     = 13,
    UNIT_IDENTITY_GERMAN_88MM_GUN  = 14,
    UNIT_IDENTITY_HOWITZER         = 15,
    UNIT_IDENTITY_ZERO_FIGHTER     = 16,
    UNIT_IDENTITY_MUSTANG_FIGHTER  = 17,
    UNIT_IDENTITY_SPITFIRE_FIGHTER = 18,
    UNIT_IDENTITY_ME109_FIGHTER    = 19,
    UNIT_IDENTITY_VAL_BOMBER       = 20,
    UNIT_IDENTITY_FLYING_FORTRESS  = 21,
    UNIT_IDENTITY_LANCASTER_BOMBER = 22,
    UNIT_IDENTITY_HEINKEL_BOMBER   = 23,
    UNIT_IDENTITY_TRIREME          = 24,
    UNIT_IDENTITY_CATAPHRACT       = 25,
    UNIT_IDENTITY_KESHIK           = 26,
    UNIT_IDENTITY_COUNT            = 27,
};

enum
{
    UNIT_DISPLAY_FORM_UNIT = 0,
    UNIT_DISPLAY_FORM_ARMY = 1,
};
