// Stable semantic IDs shared by ReRevved's public C ABIs.

#pragma once

#include <stdint.h>

typedef int32_t ReRevvedCivilizationId;
typedef int32_t ReRevvedUnitTypeId;
typedef int32_t ReRevvedUnitIdentityId;
typedef int32_t ReRevvedUnitDisplayForm;

enum
{
    REREVVED_CIVILIZATION_UNKNOWN   = -1,
    REREVVED_CIVILIZATION_ROMAN     = 0,
    REREVVED_CIVILIZATION_EGYPTIAN  = 1,
    REREVVED_CIVILIZATION_GREEK     = 2,
    REREVVED_CIVILIZATION_SPANISH   = 3,
    REREVVED_CIVILIZATION_GERMAN    = 4,
    REREVVED_CIVILIZATION_RUSSIAN   = 5,
    REREVVED_CIVILIZATION_CHINESE   = 6,
    REREVVED_CIVILIZATION_AMERICAN  = 7,
    REREVVED_CIVILIZATION_JAPANESE  = 8,
    REREVVED_CIVILIZATION_FRENCH    = 9,
    REREVVED_CIVILIZATION_INDIAN    = 10,
    REREVVED_CIVILIZATION_ARABIAN   = 11,
    REREVVED_CIVILIZATION_AZTEC     = 12,
    REREVVED_CIVILIZATION_ZULU      = 13,
    REREVVED_CIVILIZATION_MONGOLIAN = 14,
    REREVVED_CIVILIZATION_ENGLISH   = 15,
    REREVVED_CIVILIZATION_COUNT     = 16,
};

enum
{
    REREVVED_UNIT_TYPE_UNKNOWN             = -1,
    REREVVED_UNIT_TYPE_SETTLERS            = 0,
    REREVVED_UNIT_TYPE_FSETTLER            = 1,
    REREVVED_UNIT_TYPE_NAVAL_CREW          = 2,
    REREVVED_UNIT_TYPE_BARBARIAN_HOT       = 3,
    REREVVED_UNIT_TYPE_BARBARIAN_TEMPERATE = 4,
    REREVVED_UNIT_TYPE_BARBARIAN_COLD      = 5,
    REREVVED_UNIT_TYPE_WARRIOR             = 6,
    REREVVED_UNIT_TYPE_MILITIA             = 7,
    REREVVED_UNIT_TYPE_LEGION              = 8,
    REREVVED_UNIT_TYPE_ARCHER              = 9,
    REREVVED_UNIT_TYPE_RIFLEMEN            = 10,
    REREVVED_UNIT_TYPE_MODERN_INFANTRY     = 11,
    REREVVED_UNIT_TYPE_HORSEMEN            = 12,
    REREVVED_UNIT_TYPE_KNIGHTS             = 13,
    REREVVED_UNIT_TYPE_TANK                = 14,
    REREVVED_UNIT_TYPE_PHALANX             = 15,
    REREVVED_UNIT_TYPE_CATAPULT            = 16,
    REREVVED_UNIT_TYPE_CANNON              = 17,
    REREVVED_UNIT_TYPE_ARTILLERY           = 18,
    REREVVED_UNIT_TYPE_SUBMARINE           = 19,
    REREVVED_UNIT_TYPE_GALLEY              = 20,
    REREVVED_UNIT_TYPE_GALLEON             = 21,
    REREVVED_UNIT_TYPE_CRUISER             = 22,
    REREVVED_UNIT_TYPE_BATTLESHIP          = 23,
    REREVVED_UNIT_TYPE_SPACE_STATION       = 24,
    REREVVED_UNIT_TYPE_BOMBER              = 25,
    REREVVED_UNIT_TYPE_FIGHTER             = 26,
    REREVVED_UNIT_TYPE_ICBM                = 27,
    REREVVED_UNIT_TYPE_SPY                 = 28,
    REREVVED_UNIT_TYPE_COUNT               = 29,
};

enum
{
    REREVVED_UNIT_IDENTITY_BASE             = 0,
    REREVVED_UNIT_IDENTITY_JAGUAR_WARRIOR   = 1,
    REREVVED_UNIT_IDENTITY_IMPI_WARRIOR     = 2,
    REREVVED_UNIT_IDENTITY_ASHIGARU_PIKEMEN = 3,
    REREVVED_UNIT_IDENTITY_HOPLITE          = 4,
    REREVVED_UNIT_IDENTITY_LONGBOW_ARCHER   = 5,
    REREVVED_UNIT_IDENTITY_CROSSBOW_ARCHER  = 6,
    REREVVED_UNIT_IDENTITY_TREBUCHET        = 7,
    REREVVED_UNIT_IDENTITY_COSSACK_HORSEMAN = 8,
    REREVVED_UNIT_IDENTITY_SAMURAI_KNIGHT   = 9,
    REREVVED_UNIT_IDENTITY_CONQUISTADOR     = 10,
    REREVVED_UNIT_IDENTITY_PANZER_TANK      = 11,
    REREVVED_UNIT_IDENTITY_T34_TANK         = 12,
    REREVVED_UNIT_IDENTITY_SHERMAN_TANK     = 13,
    REREVVED_UNIT_IDENTITY_GERMAN_88MM_GUN  = 14,
    REREVVED_UNIT_IDENTITY_HOWITZER         = 15,
    REREVVED_UNIT_IDENTITY_ZERO_FIGHTER     = 16,
    REREVVED_UNIT_IDENTITY_MUSTANG_FIGHTER  = 17,
    REREVVED_UNIT_IDENTITY_SPITFIRE_FIGHTER = 18,
    REREVVED_UNIT_IDENTITY_ME109_FIGHTER    = 19,
    REREVVED_UNIT_IDENTITY_VAL_BOMBER       = 20,
    REREVVED_UNIT_IDENTITY_FLYING_FORTRESS  = 21,
    REREVVED_UNIT_IDENTITY_LANCASTER_BOMBER = 22,
    REREVVED_UNIT_IDENTITY_HEINKEL_BOMBER   = 23,
    REREVVED_UNIT_IDENTITY_TRIREME          = 24,
    REREVVED_UNIT_IDENTITY_CATAPHRACT       = 25,
    REREVVED_UNIT_IDENTITY_KESHIK           = 26,
    REREVVED_UNIT_IDENTITY_COUNT            = 27,
};

enum
{
    REREVVED_UNIT_DISPLAY_FORM_UNIT = 0,
    REREVVED_UNIT_DISPLAY_FORM_ARMY = 1,
};
