name = "Mongol Horseback Riding"
version = "1.0.0"
author = "Aeshur"
description = "Replaces the Mongolian Ancient UEA with Knowledge of Horseback Riding."
game_version = ">= 1.0.0"
code = "mongol_horseback_riding"
